--- #YAML:1.0
name:                App-Cache
version:             0.33
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Accessor::Chained::Fast: 0
    File::Find::Rule:              0
    File::HomeDir:                 0
    File::stat:                    0
    HTTP::Cookies:                 0
    LWP::UserAgent:                0
    Path::Class:                   0
    Storable:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Leon Brocard <acme@astray.com>
